#pragma once
#include "Renderer.h"
#include "Input.h"
#include "Collision.h"
#include "Random.h"
#include "Transform2D.h"
#include "Color.h"
#include "DrawEffects.h"
#include <Novice.h>
#define _USE_MATH_DEFINES
#include <math.h>
#include <time.h>